@extends('frontend.layout.app')
@section('title', 'Sipaten')
@section('Meta')
<meta name="description" content="Pelayanan Administrasi Online Kecamatan" />
<meta name="keywords" content="Sipaten" />
<meta property="og:title" content="Sipaten" />
<meta property="og:type" content="Sipaten" />
<meta property="og:image" content="{{asset('public/assets/default.jpg')}}" />
@endsection

@section('content')

<header class="video-header">
    {{-- <video id="welcome" src="https://css-tricks-post-videos.s3.us-east-1.amazonaws.com/Island%20-%204141.mp4" autoplay loop playsinline muted></video> --}}
    <img id="welcome" src="https://images.squarespace-cdn.com/content/v1/5a5906400abd0406785519dd/1552662149940-G6MMFW3JC2J61UBPROJ5/ke17ZwdGBToddI8pDm48kLkXF2pIyv_F2eUT9F60jBl7gQa3H78H3Y0txjaiv_0fDoOvxcdMmMKkDsyUqMSsMWxHk725yiiHCCLfrh8O1z4YTzHvnKhyp6Da-NYroOW3ZGjoBKy3azqku80C789l0iyqMbMesKd95J-X4EagrgU9L3Sa3U8cogeb0tjXbfawd0urKshkc5MgdBeJmALQKw/baelen.jpg?format=1500w" alt="">
    <div class="viewport-header">
      <h1>
        SELAMAT DATANG
        <span>SLURRR</span>
      </h1>
    </div>
</header>

@include('frontend.layout.menu')


<main>        
    <div style="padding:10px;text-align:justify;">
        
        Lorem ipsum dolor sit amet, consectetur adipiscing elit. Fusce hendrerit varius metus, non tempor tortor vehicula sed. Cras quis orci sit amet velit tincidunt pellentesque et id lacus. Aliquam a pretium dui. Donec ac posuere odio. Cras gravida, neque sed dapibus faucibus, massa ligula vulputate dui, sit amet tincidunt arcu tellus at felis. Vivamus laoreet euismod eros, vel rutrum nulla euismod ut. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Etiam viverra imperdiet purus a condimentum.
        Nam sodales id dolor sed porttitor. Morbi elementum metus sed lorem posuere rutrum. Ut non libero vel libero placerat pharetra. Phasellus maximus tellus ac auctor eleifend. Mauris nec turpis dignissim, aliquet purus non, imperdiet neque. Donec id sapien enim. Fusce faucibus, ipsum et ultrices bibendum, arcu tortor dictum tellus, sed tincidunt augue enim eget diam. Vestibulum justo risus, varius sit amet varius id, tempus et ipsum. Morbi efficitur, mauris at venenatis lacinia, risus lacus egestas urna, vel semper dolor turpis eget velit. Nam dui nibh, mattis in aliquet sed, hendrerit sit amet ipsum. Nulla nec justo eget justo facilisis finibus eget sit amet ligula.        
        Aenean non lacus venenatis, bibendum magna in, rutrum massa. Aenean scelerisque lobortis nibh ut tempus. Maecenas elit purus, tincidunt quis diam eget, rutrum dictum est. Vivamus malesuada odio non purus egestas tincidunt. Sed ac massa elementum, suscipit risus bibendum, interdum risus. Donec accumsan pharetra ipsum id pharetra. Donec consequat non ligula sed placerat. Fusce aliquet tincidunt augue, in finibus ipsum fermentum eget. Fusce enim est, elementum eget enim id, consequat pretium sem. Curabitur semper, turpis id posuere fermentum, erat sem efficitur orci, vel viverra est nunc vel ligula. In dapibus rutrum quam non ullamcorper. Cras quis molestie odio. Suspendisse finibus neque erat, eget congue orci porttitor placerat.
        Lorem ipsum dolor sit amet, consectetur adipiscing elit. Fusce hendrerit varius metus, non tempor tortor vehicula sed. Cras quis orci sit amet velit tincidunt pellentesque et id lacus. Aliquam a pretium dui. Donec ac posuere odio. Cras gravida, neque sed dapibus faucibus, massa ligula vulputate dui, sit amet tincidunt arcu tellus at felis. Vivamus laoreet euismod eros, vel rutrum nulla euismod ut. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Etiam viverra imperdiet purus a condimentum.
        Nam sodales id dolor sed porttitor. Morbi elementum metus sed lorem posuere rutrum. Ut non libero vel libero placerat pharetra. Phasellus maximus tellus ac auctor eleifend. Mauris nec turpis dignissim, aliquet purus non, imperdiet neque. Donec id sapien enim. Fusce faucibus, ipsum et ultrices bibendum, arcu tortor dictum tellus, sed tincidunt augue enim eget diam. Vestibulum justo risus, varius sit amet varius id, tempus et ipsum. Morbi efficitur, mauris at venenatis lacinia, risus lacus egestas urna, vel semper dolor turpis eget velit. Nam dui nibh, mattis in aliquet sed, hendrerit sit amet ipsum. Nulla nec justo eget justo facilisis finibus eget sit amet ligula.
        Aenean non lacus venenatis, bibendum magna in, rutrum massa. Aenean scelerisque lobortis nibh ut tempus. Maecenas elit purus, tincidunt quis diam eget, rutrum dictum est. Vivamus malesuada odio non purus egestas tincidunt. Sed ac massa elementum, suscipit risus bibendum, interdum risus. Donec accumsan pharetra ipsum id pharetra. Donec consequat non ligula sed placerat. Fusce aliquet tincidunt augue, in finibus ipsum fermentum eget. Fusce enim est, elementum eget enim id, consequat pretium sem. Curabitur semper, turpis id posuere fermentum, erat sem efficitur orci, vel viverra est nunc vel ligula. In dapibus rutrum quam non ullamcorper. Cras quis molestie odio. Suspendisse finibus neque erat, eget congue orci porttitor placerat.
        Quisque accumsan lacus vel varius viverra. Praesent sodales mattis leo. Nunc dapibus maximus rhoncus. Nam vel dolor sit amet tellus pharetra blandit. Duis in commodo massa. Vestibulum euismod tellus eu porttitor dapibus. Quisque ullamcorper turpis vitae arcu euismod eleifend vel id justo. Nam vitae mollis quam, non tincidunt lorem. Pellentesque scelerisque est id orci condimentum, non aliquet odio ullamcorper. In ultrices dapibus ornare. Aenean ultricies ex lobortis, ullamcorper tortor ut, auctor eros. Pellentesque non dolor eget ante sagittis blandit. Suspendisse est dolor, sagittis at molestie id, dictum vel elit. Praesent eget fermentum dolor, ut dictum metus. Nam malesuada turpis sed nulla convallis, ut bibendum mi eleifend. Etiam libero orci, luctus sed nibh eget, hendrerit sagittis elit.
        Donec porta, tortor ac semper aliquam, purus sapien interdum enim, nec ullamcorper eros ex a turpis. Donec porttitor nunc vitae iaculis vulputate. Pellentesque interdum, velit nec iaculis faucibus, ante orci bibendum odio, finibus suscipit lectus felis ut neque. Quisque ipsum dui, hendrerit vel semper ut, sagittis ac lectus. Proin consectetur ac leo ut ultrices. Ut sed suscipit purus. Donec dapibus, nunc vel ullamcorper hendrerit, nisl libero dictum nisi, a blandit neque nisl eu metus. Ut sollicitudin lectus odio, maximus lacinia nulla tempus sed.
        Lorem ipsum dolor sit amet, consectetur adipiscing elit. Fusce hendrerit varius metus, non tempor tortor vehicula sed. Cras quis orci sit amet velit tincidunt pellentesque et id lacus. Aliquam a pretium dui. Donec ac posuere odio. Cras gravida, neque sed dapibus faucibus, massa ligula vulputate dui, sit amet tincidunt arcu tellus at felis. Vivamus laoreet euismod eros, vel rutrum nulla euismod ut. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Etiam viverra imperdiet purus a condimentum.
        Nam sodales id dolor sed porttitor. Morbi elementum metus sed lorem posuere rutrum. Ut non libero vel libero placerat pharetra. Phasellus maximus tellus ac auctor eleifend. Mauris nec turpis dignissim, aliquet purus non, imperdiet neque. Donec id sapien enim. Fusce faucibus, ipsum et ultrices bibendum, arcu tortor dictum tellus, sed tincidunt augue enim eget diam. Vestibulum justo risus, varius sit amet varius id, tempus et ipsum. Morbi efficitur, mauris at venenatis lacinia, risus lacus egestas urna, vel semper dolor turpis eget velit. Nam dui nibh, mattis in aliquet sed, hendrerit sit amet ipsum. Nulla nec justo eget justo facilisis finibus eget sit amet ligula.        
        Aenean non lacus venenatis, bibendum magna in, rutrum massa. Aenean scelerisque lobortis nibh ut tempus. Maecenas elit purus, tincidunt quis diam eget, rutrum dictum est. Vivamus malesuada odio non purus egestas tincidunt. Sed ac massa elementum, suscipit risus bibendum, interdum risus. Donec accumsan pharetra ipsum id pharetra. Donec consequat non ligula sed placerat. Fusce aliquet tincidunt augue, in finibus ipsum fermentum eget. Fusce enim est, elementum eget enim id, consequat pretium sem. Curabitur semper, turpis id posuere fermentum, erat sem efficitur orci, vel viverra est nunc vel ligula. In dapibus rutrum quam non ullamcorper. Cras quis molestie odio. Suspendisse finibus neque erat, eget congue orci porttitor placerat.
        Lorem ipsum dolor sit amet, consectetur adipiscing elit. Fusce hendrerit varius metus, non tempor tortor vehicula sed. Cras quis orci sit amet velit tincidunt pellentesque et id lacus. Aliquam a pretium dui. Donec ac posuere odio. Cras gravida, neque sed dapibus faucibus, massa ligula vulputate dui, sit amet tincidunt arcu tellus at felis. Vivamus laoreet euismod eros, vel rutrum nulla euismod ut. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Etiam viverra imperdiet purus a condimentum.
        Nam sodales id dolor sed porttitor. Morbi elementum metus sed lorem posuere rutrum. Ut non libero vel libero placerat pharetra. Phasellus maximus tellus ac auctor eleifend. Mauris nec turpis dignissim, aliquet purus non, imperdiet neque. Donec id sapien enim. Fusce faucibus, ipsum et ultrices bibendum, arcu tortor dictum tellus, sed tincidunt augue enim eget diam. Vestibulum justo risus, varius sit amet varius id, tempus et ipsum. Morbi efficitur, mauris at venenatis lacinia, risus lacus egestas urna, vel semper dolor turpis eget velit. Nam dui nibh, mattis in aliquet sed, hendrerit sit amet ipsum. Nulla nec justo eget justo facilisis finibus eget sit amet ligula.
        Aenean non lacus venenatis, bibendum magna in, rutrum massa. Aenean scelerisque lobortis nibh ut tempus. Maecenas elit purus, tincidunt quis diam eget, rutrum dictum est. Vivamus malesuada odio non purus egestas tincidunt. Sed ac massa elementum, suscipit risus bibendum, interdum risus. Donec accumsan pharetra ipsum id pharetra. Donec consequat non ligula sed placerat. Fusce aliquet tincidunt augue, in finibus ipsum fermentum eget. Fusce enim est, elementum eget enim id, consequat pretium sem. Curabitur semper, turpis id posuere fermentum, erat sem efficitur orci, vel viverra est nunc vel ligula. In dapibus rutrum quam non ullamcorper. Cras quis molestie odio. Suspendisse finibus neque erat, eget congue orci porttitor placerat.
        Quisque accumsan lacus vel varius viverra. Praesent sodales mattis leo. Nunc dapibus maximus rhoncus. Nam vel dolor sit amet tellus pharetra blandit. Duis in commodo massa. Vestibulum euismod tellus eu porttitor dapibus. Quisque ullamcorper turpis vitae arcu euismod eleifend vel id justo. Nam vitae mollis quam, non tincidunt lorem. Pellentesque scelerisque est id orci condimentum, non aliquet odio ullamcorper. In ultrices dapibus ornare. Aenean ultricies ex lobortis, ullamcorper tortor ut, auctor eros. Pellentesque non dolor eget ante sagittis blandit. Suspendisse est dolor, sagittis at molestie id, dictum vel elit. Praesent eget fermentum dolor, ut dictum metus. Nam malesuada turpis sed nulla convallis, ut bibendum mi eleifend. Etiam libero orci, luctus sed nibh eget, hendrerit sagittis elit.
        Donec porta, tortor ac semper aliquam, purus sapien interdum enim, nec ullamcorper eros ex a turpis. Donec porttitor nunc vitae iaculis vulputate. Pellentesque interdum, velit nec iaculis faucibus, ante orci bibendum odio, finibus suscipit lectus felis ut neque. Quisque ipsum dui, hendrerit vel semper ut, sagittis ac lectus. Proin consectetur ac leo ut ultrices. Ut sed suscipit purus. Donec dapibus, nunc vel ullamcorper hendrerit, nisl libero dictum nisi, a blandit neque nisl eu metus. Ut sollicitudin lectus odio, maximus lacinia nulla tempus sed.
        Lorem ipsum dolor sit amet, consectetur adipiscing elit. Fusce hendrerit varius metus, non tempor tortor vehicula sed. Cras quis orci sit amet velit tincidunt pellentesque et id lacus. Aliquam a pretium dui. Donec ac posuere odio. Cras gravida, neque sed dapibus faucibus, massa ligula vulputate dui, sit amet tincidunt arcu tellus at felis. Vivamus laoreet euismod eros, vel rutrum nulla euismod ut. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Etiam viverra imperdiet purus a condimentum.
        Nam sodales id dolor sed porttitor. Morbi elementum metus sed lorem posuere rutrum. Ut non libero vel libero placerat pharetra. Phasellus maximus tellus ac auctor eleifend. Mauris nec turpis dignissim, aliquet purus non, imperdiet neque. Donec id sapien enim. Fusce faucibus, ipsum et ultrices bibendum, arcu tortor dictum tellus, sed tincidunt augue enim eget diam. Vestibulum justo risus, varius sit amet varius id, tempus et ipsum. Morbi efficitur, mauris at venenatis lacinia, risus lacus egestas urna, vel semper dolor turpis eget velit. Nam dui nibh, mattis in aliquet sed, hendrerit sit amet ipsum. Nulla nec justo eget justo facilisis finibus eget sit amet ligula.        
        Aenean non lacus venenatis, bibendum magna in, rutrum massa. Aenean scelerisque lobortis nibh ut tempus. Maecenas elit purus, tincidunt quis diam eget, rutrum dictum est. Vivamus malesuada odio non purus egestas tincidunt. Sed ac massa elementum, suscipit risus bibendum, interdum risus. Donec accumsan pharetra ipsum id pharetra. Donec consequat non ligula sed placerat. Fusce aliquet tincidunt augue, in finibus ipsum fermentum eget. Fusce enim est, elementum eget enim id, consequat pretium sem. Curabitur semper, turpis id posuere fermentum, erat sem efficitur orci, vel viverra est nunc vel ligula. In dapibus rutrum quam non ullamcorper. Cras quis molestie odio. Suspendisse finibus neque erat, eget congue orci porttitor placerat.
        Lorem ipsum dolor sit amet, consectetur adipiscing elit. Fusce hendrerit varius metus, non tempor tortor vehicula sed. Cras quis orci sit amet velit tincidunt pellentesque et id lacus. Aliquam a pretium dui. Donec ac posuere odio. Cras gravida, neque sed dapibus faucibus, massa ligula vulputate dui, sit amet tincidunt arcu tellus at felis. Vivamus laoreet euismod eros, vel rutrum nulla euismod ut. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Etiam viverra imperdiet purus a condimentum.
        Nam sodales id dolor sed porttitor. Morbi elementum metus sed lorem posuere rutrum. Ut non libero vel libero placerat pharetra. Phasellus maximus tellus ac auctor eleifend. Mauris nec turpis dignissim, aliquet purus non, imperdiet neque. Donec id sapien enim. Fusce faucibus, ipsum et ultrices bibendum, arcu tortor dictum tellus, sed tincidunt augue enim eget diam. Vestibulum justo risus, varius sit amet varius id, tempus et ipsum. Morbi efficitur, mauris at venenatis lacinia, risus lacus egestas urna, vel semper dolor turpis eget velit. Nam dui nibh, mattis in aliquet sed, hendrerit sit amet ipsum. Nulla nec justo eget justo facilisis finibus eget sit amet ligula.
        Aenean non lacus venenatis, bibendum magna in, rutrum massa. Aenean scelerisque lobortis nibh ut tempus. Maecenas elit purus, tincidunt quis diam eget, rutrum dictum est. Vivamus malesuada odio non purus egestas tincidunt. Sed ac massa elementum, suscipit risus bibendum, interdum risus. Donec accumsan pharetra ipsum id pharetra. Donec consequat non ligula sed placerat. Fusce aliquet tincidunt augue, in finibus ipsum fermentum eget. Fusce enim est, elementum eget enim id, consequat pretium sem. Curabitur semper, turpis id posuere fermentum, erat sem efficitur orci, vel viverra est nunc vel ligula. In dapibus rutrum quam non ullamcorper. Cras quis molestie odio. Suspendisse finibus neque erat, eget congue orci porttitor placerat.
        Quisque accumsan lacus vel varius viverra. Praesent sodales mattis leo. Nunc dapibus maximus rhoncus. Nam vel dolor sit amet tellus pharetra blandit. Duis in commodo massa. Vestibulum euismod tellus eu porttitor dapibus. Quisque ullamcorper turpis vitae arcu euismod eleifend vel id justo. Nam vitae mollis quam, non tincidunt lorem. Pellentesque scelerisque est id orci condimentum, non aliquet odio ullamcorper. In ultrices dapibus ornare. Aenean ultricies ex lobortis, ullamcorper tortor ut, auctor eros. Pellentesque non dolor eget ante sagittis blandit. Suspendisse est dolor, sagittis at molestie id, dictum vel elit. Praesent eget fermentum dolor, ut dictum metus. Nam malesuada turpis sed nulla convallis, ut bibendum mi eleifend. Etiam libero orci, luctus sed nibh eget, hendrerit sagittis elit.
        Donec porta, tortor ac semper aliquam, purus sapien interdum enim, nec ullamcorper eros ex a turpis. Donec porttitor nunc vitae iaculis vulputate. Pellentesque interdum, velit nec iaculis faucibus, ante orci bibendum odio, finibus suscipit lectus felis ut neque. Quisque ipsum dui, hendrerit vel semper ut, sagittis ac lectus. Proin consectetur ac leo ut ultrices. Ut sed suscipit purus. Donec dapibus, nunc vel ullamcorper hendrerit, nisl libero dictum nisi, a blandit neque nisl eu metus. Ut sollicitudin lectus odio, maximus lacinia nulla tempus sed.
    </div>
</main>
@include('frontend.layout.footer')
@endsection

@section('top-resource')
<style>
h1 {
  font-family: 'Syncopate', sans-serif;
  color: white;
  text-transform: uppercase;
  letter-spacing: 3vw;
  line-height: 1.5;
  font-size: 4vw;
  text-align: center;
  -webkit-text-stroke: 1px #222;
  span {
    display: block;
    font-size: 10vw;
    letter-spacing: -1.3vw;
  }
}
</style>    
@endsection
@section('bottom-resource')

@endsection